### ISSUE TITLE
erreur pour sortir de la messagerie

### ISSUE THREAD

**Issue by remikaze** [emeric254/Java-STRI-S4#50]
Quand on veut sortir de la messagerie en faisant 0 (cf. menu "afficherMenuMessagerie") il ne se passe rien, on reste coincé dans la boucle avec : 

` = = = Menu messagerie (vous etes connecté) = = = 
Bonjour Emeric TOSI
 Saisissez votre choix :

 =>  1 - Messagerie directe.

 =>  2 - Messagerie indirecte.

 =>  3 - Afficher les messages en attente.

 =>  0 - Quitter.
0

Veuillez choisir quelque chose de valide !

0
0
o
O
0
0
0
`

**Comment by emeric254** [comment]
commit 810e2fa7569076c53b431ae2b04440bbefab594b
